databases:
  - name: health-sync-db
    plan: free
    databaseName: healthsync

services:
  - type: web
    name: health-sync
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d7e7oafaqgkc7382bos0-a/health_sync_gclz
      - key: DB_USERNAME
        value: health_sync_gclz_user
      - key: DB_PASSWORD
        value: Jrk6IpN0aJyK8xnByaLXfZfl6Ju2yIeK
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: FEISHU_WEBHOOK_URL
        sync: false
      - key: PUSHPLUS_TOKEN
        sync: false